from State_EX_Som import Sound

sound = Sound()
sound.pess_next()
sound.pess_prev()
sound.pess_change_mode()
sound.pess_next()
sound.pess_next()
sound.pess_next()
sound.pess_prev()
sound.pess_change_mode()
sound.microphone_mode()
sound.pess_next()
sound.pess_next()
sound.pess_next()
sound.pess_next()
sound.pess_next()
sound.pess_next()
sound.pess_prev()
sound.pess_change_mode()
sound.pess_next()
sound.pess_next()
sound.pess_next()
sound.pess_next()
sound.pess_prev()
sound.pess_prev()
sound.pess_prev()
sound.pess_change_mode()
sound.pess_next()
